version: '2.1'
services:
    backend:
        build: ./my-vue-backend
        entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
        ports:
            - "8081:8081"
        healthcheck:
            test: "exit 0"
    
    frontend:
        build: ./my-vue-app
        depends_on:
            backend:
                condition: service_healthy
        entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
        ports:
            - "8080:8080"